name: test
on:
  push:
    branches: [ master ]
  pull_request:

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: actions/setup-node@v4
      with:
        cache: npm
    - run: npm i @ui5/cli --ignore-scripts
    - run: npm ci --ignore-scripts
    - run: npm run build
    - run: npm run lint:ci
    - run: npm run test:ci
    - uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: target/eslint.sarif
